language: java
os: linux
dist: bionic
jdk:
  - openjdk8
env:
  - DISPLAY=:99.0
services:
  - xvfb
before_install:
  - export WORKSPACE=${PWD}
  - sudo apt-get -y install at-spi2-core
script: mvn clean verify checkstyle:check pmd:check pmd:cpd-check findbugs:check -f ./ddk-parent/pom.xml --batch-mode --fail-at-end
